### ISSUE TITLE
ブログ内容の出力方法について

### ISSUE THREAD

**Issue by k-logic563** [kananilai/qin-portfolio#23]
@kananilai 

https://github.com/kananilai/qin-portfolio/blob/ec4645d7dad726a99c56c5d5c2b5d034acecbc75/src/components/Blog.jsx#L17

replaceを使用してタグを置き換えている様子ですね！
これ、microcms側でapiスキーマ追加して出力した方が後々便利かと思います。

例えば、descriptionといったスキーマを追加し、そこに記事の要約を書く。複数業テキストフィールドです。
それを出力すればタグを置き換える必要もないかなと思われます。

また、要約を設けることでSEOに必須のディスクリプションを設定することができます。

**Comment by kananilai** [comment]
検討します。
ありがとうございました。
