### ISSUE TITLE
Twitter API繋ぎ込み

### ISSUE THREAD

**Issue by kananilai** [kananilai/qin-portfolio#28]
### やったこと
- twitter-api-sdkを用いて、ツイート取得

mergeしてしまったので、mainブランチを見ていただきたいです！
https://github.com/kananilai/qin-portfolio/tree/main

よろしくお願いいたします🙇‍♂️

**Comment by kyoichi1** [comment]
お疲れ様です✨
コードがとても綺麗で感動しておりました🙇‍♂️✨
SWRのところやエラー処理もすごく丁寧にされていて大変勉強になりました🙏
私のスキルが低すぎて技術的なところの指摘やアドバイス等でお力になれずすみません。

微かなスキルで気になったところだけお伝えさせて頂きますので、
さらっと流して頂いて構いませんので、お時間あればご確認よろしくお願い致します🙇‍♂️✨

✅　表示件数について
今回のTwitterのリストに関しては10件をデフォルトで取ってくるようになってるかと思います。

【src>pages>api>twitter.js】

      const recentSearch = await twitterClient.tweets.tweetsRecentSearch({
      query: "(from:TDR_PR)",
      expansions: ["author_id"],
      "tweet.fields": ["created_at"],
      max_results: 10,　👈(10行目)
    });

Twtter Cardでは3件のみ表示されている状態になっているかと思います。

【src>components>TwitterCard.jsx】

      return (
           <div>
             {data?.data.slice(0, 3).map((tweet) =>( 👈(27行目)
           <div className="my-2 mt-5 flex" key={tweet.id}>


データを10件すでに取って来ているので10件スクロールで表示されるか
３件しか表示させないのであれば、取ってくる件数を３件にされる方が無駄がなくなるのかな〜と思いました👀
個人的にはツイートの高さ的はツイーの文字数で変わってしまうので３件に指定すると
ツイートリストの高さが変動しちゃうので、
レイアウト的なところから見るとGitHubの表示とTwitterの高さを合わせて、
その内部でスクロールさせて表示されるのが良いのかなと思いました😂


tailwindcssで`overflow-y-auto`サクッとできるのでお勧めです😆
https://tailwindcss.com/docs/overflow




✅　APIについてtwitter.jsとtwitterIcon.jsでそれぞれでAPIを叩かれているかと思いすが、
どちらもTWITTER_BEARER_TOKENが承認されて表示されるものになり、ICONやidやtextについても
同時に表示が必要になるので、まとめてもリクエストしても良いのかな〜と個人的に思いました。
（まとめた方が１回のリクエストで行けるので早くなるかと思ったのですが、正式には分けたが方が良いのかもしれないのでリリーさんにここは確認して頂いた方が良いかもです....😅）


【pages>api>twitter.js】

```
const getTwitter = async (req, res) => {
  try {
    const twitterClient = new Client(process.env.TWITTER_BEARER_TOKEN);　👈
    const recentSearch = await twitterClient.tweets.tweetsRecentSearch({
      query: "(from:TDR_PR)",
      expansions: ["author_id"],
      "tweet.fields": ["created_at"],
      max_results: 10,
    });
```

【pages>api>twitterIcon.js】

```
const getTwitterIcon = async (req, res) => {
  try {
    const twitterClient = new Client(process.env.TWITTER_BEARER_TOKEN);　👈
    const usernamesLookup = await twitterClient.users.findUsersByUsername({
      usernames: ["TDR_PR"],
      "user.fields": ["profile_image_url"],
    });
    res.status(200).json(usernamesLookup);
  } catch (error) {
    console.log(error);
    console.error(err);
    res.statusCode = 500;
  }
};
```



✅　レイアウトについて

【components>TwitterCard.jsx 】


アイコンの表示についてradiusが”lg”で指定されているので今楕円形になっているので、
`rounded-full`等でに◯にされるのが良いかと☺️
https://tailwindcss.com/docs/border-radius


  `      <Avatar src={icon_url} alt="it's me" radius="lg" className="mr-2" />`👈


またレスポンシブの対応についてですが、現在モバイルからwidthが992px（タブレット）サイズまでが
ブログと同様に画面いっぱい表示されていますので、Twitter公式のレイアウトな感じをmax-width等でされると良いかなーと思いました🙏✨
（ちなみに偉そうに言ってますが、自分もレイアウトの修正全く追いついて無いです( ͡° ͜ʖ ͡°)）

<br>
<br>
<br>
上記３点になりますが、「いや！その指摘間違ってますよw全く的外れなんですけど😂」って
思われるの覚悟で勇気を振り絞ってコメントさせて頂いてますので😂
あくまででも初心者の戯言とて捉えていただければと思いますので宜しくお願い致します🙏😆

<br>
<br>
<br>

**Comment by shu-illy** [comment]
お疲れ様です！

すでにマージ済ですが、こちらのPRにコメントさせて頂きました🙏
https://github.com/kananilai/qin-portfolio/pull/26#pullrequestreview-1105672758

> （まとめた方が１回のリクエストで行けるので早くなるかと思ったのですが、正式には分けたが方が良いのかもしれないのでリリーさんにここは確認して頂いた方が良いかもです....😅）

なるべくリクエスト数少ない方がいいのはその通りですね！
ただ、usernameをパラメータとした場合にツイートまで1件で取得できるかが僕もよく分からず…（僕の場合はユーザーIDを既知の値として扱ってたので😂）
少なくとも`users/by/username`のエンドポイントでは固定ツイしか取得できなさそうですね…🥲
